use_frameworks!

platform :ios, '8.0'

target 'CDFont_Example' do
  pod 'CDFont', :path => '../'

  target 'CDFont_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
